version: '3'
services:
  php:
    build: ./docker/php
    volumes:
        - ./:/usr/share/nginx/www
    working_dir: /usr/share/nginx/www
    env_file:
      - ./development.env

  nginx:
    build: ./docker/nginx
    links:
        - php
    volumes:
        - ./:/usr/share/nginx/www
    ports:
      - 80:80
    depends_on:
      - mysql
      - php

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    env_file:
      - ./development.env
    depends_on:
      - php
  
  
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "logs:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
